name: deploy to github pages

on:
  push:
    branches:
      -main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      #checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3
      
      #setup noodejs
      - name: Setup Node.js
        uses: actions/setupnode@v3
        with: 
          node-version: 18
      
      #install depedencies
      - name: Install Depedencies
        run: npm install
      
      #build project
      - name: Build Project
        run: npm run build
      
      #deploy to gh-pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets }}
          publish_dir: dist
          
      
      
      
      
